---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codeserver-cm
  labels:
    app: codeserver
    name: codeserver-cm
  namespace: codeserverns
data:
  PUID: "1000"
  PGID: "1000"
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
---
# apiVersion: v1 
# kind: Secret 
# metadata: 
#   name: codeserver-secret
#   namespace: codeserverns
# type: Opaque 
# data:
#   BGG_DB_PASSWORD: Y2hhbmdlaXQ=