---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-pvc
  labels:
    app: codeserver
    name: codeserver-pvc
  namespace: codeserverns
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: do-block-storage-xfs
  resources:
    requests:
      storage: 1Gi