---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: db-deploy 
  labels:
    name: db-deploy
  namespace: bggns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db-po
  template:
    metadata:
      name: db-po
      labels:
        name: db-po
      namespace: bggns
    spec:
      containers:
      - name: db-container
        image: stackupiss/bgg-database:v1 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306

---
apiVersion: v1 
kind: Service 
metadata:
  name: db-svc 
  labels:
    name: db-svc 
  namespace: bggns
spec:
  type: ClusterIP
  selector:
    name: db-po
  ports:
  - port: 3306
    targetPort: 3306